/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  account_type: string;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  holdings_public: Generated<boolean>;
  id: string;
  is_master: Generated<boolean>;
  modified_at: Generated<Timestamp>;
  name: string;
  native_account_id: string | null;
  opened_on: Timestamp | null;
  organisation_id: string | null;
  parent_account_id: string | null;
  registry_id: string;
  retirements_public: Generated<boolean>;
  standard_id: string | null;
  status: Generated<string>;
  version: Generated<number>;
}

export interface Agreement {
  agreement_type: string;
  collateral_type: Generated<string[]>;
  commitment_amount: Numeric | null;
  created_at: Generated<Timestamp>;
  currency: string | null;
  effective_on: Timestamp | null;
  expiry_on: Timestamp | null;
  financing_stage: string | null;
  governing_law: string | null;
  id: string;
  marketplace_or_venue: Generated<string[]>;
  modified_at: Generated<Timestamp>;
  notes: string | null;
  project_id: string;
  version: Generated<number>;
}

export interface AgreementCounterparty {
  agreement_id: string;
  organisation_id: string;
  role: string;
  sector: string | null;
}

export interface AgreementFunding {
  agreement_id: string;
  commitment_status: string | null;
  conditions_precedent: string | null;
  disbursement_schedule: string | null;
  expected_disbursement_on: Timestamp | null;
  id: string;
  is_current: Generated<boolean>;
  is_fully_committed: boolean | null;
  sequence: number;
  source_category: string;
  status_reason: string | null;
}

export interface AgreementInsurance {
  agreement_id: string;
  coverage_type: string | null;
  id: string;
  insurer_name: string | null;
  policy_exists: boolean;
  policy_reference: string | null;
}

export interface AgreementOfftake {
  agreement_id: string;
  contracted_price: Numeric | null;
  contracted_volume: Int8 | null;
  id: string;
  requirements: string | null;
  vintage_end_year: number | null;
  vintage_start_year: number | null;
}

export interface ApiKey {
  account_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  key_hash: string;
  label: string;
  last_used_at: Timestamp | null;
  revoked_at: Timestamp | null;
  role: string;
}

export interface BufferPoolBalance {
  deposits: Numeric | null;
  project_id: string | null;
  releases: Numeric | null;
  reversal_coverage: Numeric | null;
  reversal_non_coverage: Numeric | null;
  standard_id: string | null;
}

export interface BufferPoolEntry {
  block_id: string | null;
  id: string;
  kind: string;
  notes: string | null;
  occurred_on: Timestamp;
  project_id: string;
  quantity: Numeric;
  standard_id: string;
  verification_event_id: string | null;
}

export interface Cancellation {
  account_id: string | null;
  block_id: string;
  cancelled_at: Timestamp;
  created_at: Generated<Timestamp>;
  detail: string | null;
  id: string;
  modified_at: Generated<Timestamp>;
  project_id: string;
  quantity: Int8;
  reason: string;
  replacement_block_id: string | null;
  version: Generated<number>;
}

export interface CdopVocabulary {
  cdop_field_id: number | null;
  cdop_field_path: string | null;
  sort: number;
  term: string;
  vocabulary: string;
}

export interface CobenefitImpact {
  achieved_impact: string | null;
  achieved_value: string | null;
  change_type: string | null;
  id: string;
  project_id: string;
  reported_on: Timestamp | null;
  supporting_evidence_url: string | null;
  target_id: string;
  verification_event_id: string | null;
}

export interface CobenefitMethod {
  method: string;
  project_id: string;
  sort: Generated<number>;
}

export interface CobenefitTarget {
  approach: string | null;
  baseline_value: string | null;
  cobenefit_type: string;
  id: string;
  impact_overview: string | null;
  indicator_id: string;
  monitoring_frequency: string | null;
  project_id: string;
  supporting_evidence_url: string | null;
  target_value: string | null;
  unit_description: string | null;
  unit_symbol: string | null;
  unit_type: string | null;
}

export interface CreditingPeriod {
  duration_years: number;
  end_on: Timestamp;
  id: string;
  is_current: Generated<boolean>;
  number: number;
  period_type: string;
  project_id: string;
  start_on: Timestamp;
  validation_event_id: string | null;
}

export interface CreditingProgram {
  cdop_name: string;
  id: string;
  url: string | null;
}

export interface Document {
  content_type: Generated<string>;
  created_at: Generated<Timestamp>;
  document_date: Timestamp | null;
  document_type_id: string;
  extracted: Generated<Json>;
  file_name: string;
  id: string;
  is_public: Generated<boolean>;
  issuance_id: string | null;
  modified_at: Generated<Timestamp>;
  project_id: string;
  sha256: string | null;
  size_bytes: number | null;
  title: string;
  uploaded_at: Timestamp;
  uploaded_by_account_id: string | null;
  url: string | null;
  validation_event_id: string | null;
  verification_event_id: string | null;
  version: Generated<number>;
  version_label: string | null;
}

export interface DocumentType {
  cdop_type: string | null;
  id: string;
  kind: string;
  name: string;
  native_id: string | null;
  stage: string | null;
  standard_id: string | null;
}

export interface Estimation {
  annual_mitigation: Numeric | null;
  created_at: Generated<Timestamp>;
  event_on: Timestamp;
  id: string;
  is_current: Generated<boolean>;
  modified_at: Generated<Timestamp>;
  project_id: string;
  sequence: number;
  status: string;
  status_reason: string | null;
  superseded_by_estimation_id: string | null;
  total_mitigation: Numeric | null;
  total_years: number | null;
  validated_by_validation_event_id: string | null;
  version: Generated<number>;
}

export interface EstimationVintage {
  estimated_buffer: Numeric | null;
  estimated_claimable: Numeric | null;
  estimated_issuance_on: Timestamp | null;
  estimated_mitigation: Numeric;
  estimation_id: string;
  id: string;
  monitoring_end_on: Timestamp | null;
  monitoring_start_on: Timestamp | null;
  project_id: string;
  vintage_end_on: Timestamp;
  vintage_start_on: Timestamp;
  vintage_year: number;
}

export interface Event {
  actor_account_id: string | null;
  actor_kind: string | null;
  causation_id: string | null;
  correlation_id: string | null;
  data: Generated<Json>;
  dedupe_key: string | null;
  id: string;
  occurred_at: Timestamp;
  origin: string;
  project_id: string | null;
  recorded_at: Generated<Timestamp>;
  sequence: Generated<Int8>;
  source: string;
  specversion: Generated<string>;
  subject: string;
  subject_type: string;
  type: string;
  xact_id: Generated<string>;
}

export interface GeolocationFile {
  area_ha: Numeric | null;
  area_type: string;
  created_at: Generated<Timestamp>;
  crs: Generated<string>;
  file_created_at: Timestamp;
  file_deleted_at: Timestamp | null;
  file_edited_at: Timestamp | null;
  file_format: string;
  file_name: string;
  file_status: string;
  geojson: Json;
  geometry_type: string;
  id: string;
  max_lat: Numeric;
  max_lon: Numeric;
  min_lat: Numeric;
  min_lon: Numeric;
  modified_at: Generated<Timestamp>;
  project_id: string;
  sha256: string | null;
  validity_end_on: Timestamp | null;
  validity_start_on: Timestamp;
  version: Generated<number>;
}

export interface IdempotencyKey {
  api_key_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  key: string;
  request_hash: string;
  response: Json | null;
  status: number | null;
}

export interface Issuance {
  batch_identifier: string;
  created_at: Generated<Timestamp>;
  cumulative_volume: Numeric;
  id: string;
  issued_on: Timestamp | null;
  kind: string;
  metric: Generated<string>;
  modified_at: Generated<Timestamp>;
  project_id: string;
  recipient_account_id: string | null;
  requested_on: Timestamp | null;
  sequence: number;
  status: string;
  unit_class: string;
  unit_type: string;
  url: string | null;
  validation_event_id: string | null;
  verification_event_id: string | null;
  version: Generated<number>;
  vintage_end_on: Timestamp;
  vintage_label: string;
  vintage_start_on: Timestamp;
  volume: Numeric;
}

export interface Label {
  cdop_enum_value: string | null;
  id: string;
  issuer: string | null;
  level: string;
  name: string;
  url: string | null;
}

export interface LifecycleTransition {
  action: string;
  actor: string;
  emits_event: string;
  entity: string;
  from_state: string;
  label: string;
  to_state: string;
}

export interface Methodology {
  cdop_name: string;
  code: string | null;
  id: string;
  sector: string | null;
  standard_id: string | null;
  title: string | null;
  url: string | null;
}

export interface MethodologyVersion {
  document_url: string | null;
  effective_on: Timestamp | null;
  id: string;
  is_current: Generated<boolean>;
  methodology_id: string;
  version: string;
}

export interface Milestone {
  completed_at: Timestamp | null;
  completed_by_validation_event_id: string | null;
  completed_by_verification_event_id: string | null;
  created_at: Generated<Timestamp>;
  due_on: Timestamp;
  id: string;
  kind: string;
  modified_at: Generated<Timestamp>;
  name: string;
  project_id: string;
  sequence: Generated<number>;
  version: Generated<number>;
}

export interface NativeState {
  cdop_project_status: string;
  code: string;
  is_terminal: Generated<boolean>;
  lifecycle_state: string;
  name: string;
  owner_actor: string;
  phase: string | null;
  sort: Generated<number>;
  standard_id: string;
}

export interface NativeTransition {
  action: string;
  actor: string;
  from_code: string;
  intent: string;
  label: string;
  requires_reason: Generated<boolean>;
  standard_id: string;
  to_code: string;
}

export interface Organisation {
  address_line_1: string | null;
  cdop_role: string | null;
  city: string | null;
  classification: string | null;
  country_code: string;
  country_name: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  employees: number | null;
  founded_on: Timestamp | null;
  id: string;
  legal_name: string;
  mission: string | null;
  modified_at: Generated<Timestamp>;
  phone: string | null;
  postal_code: string | null;
  project_employees: number | null;
  project_experience_years: number | null;
  region_code: string | null;
  region_name: string | null;
  subdivision_code: string | null;
  subdivision_name: string | null;
  team_experience: string | null;
  trading_name: string | null;
  version: Generated<number>;
  website: string | null;
}

export interface Project {
  activity_type: string | null;
  area_ha: Numeric | null;
  attestations: Generated<Json>;
  buffer_rate: Numeric | null;
  cdop_project_status: string;
  centroid_lat: Numeric | null;
  centroid_lon: Numeric | null;
  city: string | null;
  closed_on: Timestamp | null;
  community_frameworks: string | null;
  country_code: string;
  country_name: string;
  created_at: Generated<Timestamp>;
  crediting_period_type: string | null;
  crediting_program_id: string;
  description: string | null;
  developer_account_id: string | null;
  developer_organisation_id: string | null;
  duration_years: number | null;
  end_on: Timestamp | null;
  estimated_annual_mitigation: Numeric | null;
  estimated_total_mitigation: Numeric | null;
  estimated_total_years: number | null;
  first_verified_on: Timestamp | null;
  governance_structure: string | null;
  grid_reference: string | null;
  id: string;
  is_on_hold: Generated<boolean>;
  lifecycle_state: string;
  listed_on: Timestamp | null;
  master_project_id: string | null;
  max_crediting_periods: number | null;
  max_cumulative_crediting_years: number | null;
  max_lat: Numeric | null;
  max_lon: Numeric | null;
  methodology_version_id: string | null;
  min_lat: Numeric | null;
  min_lon: Numeric | null;
  modified_at: Generated<Timestamp>;
  name: string;
  native_attributes: Generated<Json>;
  native_project_id: string;
  native_project_url: string | null;
  native_state_code: string;
  native_state_name: string | null;
  previous_program: boolean | null;
  program_type: string | null;
  project_identifier: string;
  project_risk: Json | null;
  public_comment: boolean | null;
  public_comment_summary: string | null;
  region_code: string;
  region_name: string;
  registered_on: Timestamp | null;
  registry_id: string;
  standard_id: string;
  standard_version_id: string | null;
  start_on: Timestamp | null;
  subdivision_code: string | null;
  subdivision_name: string | null;
  unit_metric: Generated<string>;
  validated_on: Timestamp | null;
  validation_deadline_on: Timestamp | null;
  version: Generated<number>;
  vvb_organisation_id: string | null;
}

export interface ProjectFinance {
  community_benefit_mechanisms: Generated<string[]>;
  currency: string | null;
  declaring_entity_organisation_id: string | null;
  expected_annual_costs: Numeric | null;
  expected_annual_revenue: Numeric | null;
  expected_community_proceeds: Numeric | null;
  expected_credit_price: Numeric | null;
  expected_initial_costs: Numeric | null;
  financing_options: Generated<string[]>;
  project_id: string;
  realized_transaction_price: Numeric | null;
  total_funding_required: Numeric | null;
  total_funding_secured: Numeric | null;
}

export interface ProjectLabel {
  accreditation_id: string | null;
  approved_on: Timestamp | null;
  expiry_on: Timestamp | null;
  id: string;
  kind: string;
  label_id: string;
  project_id: string;
  start_on: Timestamp | null;
  url: string | null;
}

export interface ProjectLandowner {
  name: string;
  project_id: string;
  sort: Generated<number>;
}

export interface ProjectLocation {
  address_line_1: string | null;
  address_line_2: string | null;
  alternative_address: string | null;
  city: string | null;
  country_code: string;
  country_name: string;
  id: string;
  is_primary: Generated<boolean>;
  kind: string;
  postal_code: string | null;
  project_id: string;
  region_code: string;
  region_name: string;
  sort: Generated<number>;
  subdivision_code: string | null;
  subdivision_name: string | null;
}

export interface ProjectMitigation {
  estimated_annual_mitigation: Numeric;
  estimated_total_mitigation: Numeric;
  id: string;
  mitigation_type: string;
  project_id: string;
  project_sector: string;
  project_type: string;
  sort: Generated<number>;
}

export interface ProjectRegistryHistory {
  crediting_program_id: string | null;
  id: string;
  previous_registration_id: string | null;
  project_id: string;
  rejection_on: Timestamp | null;
  rejection_reason: string | null;
}

export interface ProjectSdg {
  project_id: string;
  sdg_number: number;
}

export interface ProjectStakeholder {
  id: string;
  is_primary_developer: Generated<boolean>;
  organisation_id: string;
  project_id: string;
  role_ended_on: Timestamp | null;
  role_started_on: Timestamp | null;
  stakeholder_type: string;
}

export interface ProjectStatusHistory {
  action: string | null;
  actor_account_id: string | null;
  actor_kind: string;
  cdop_project_status: string;
  effective_at: Timestamp;
  event_id: string | null;
  id: string;
  intent: string | null;
  is_current: Generated<boolean>;
  lifecycle_state: string;
  native_state_code: string;
  native_state_name: string | null;
  project_id: string;
  reason: string | null;
  recorded_at: Generated<Timestamp>;
  sequence: number;
}

export interface Registry {
  cdop_name: string;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  modified_at: Generated<Timestamp>;
  operator_name: string | null;
  project_url_template: string | null;
  serial_grammar: string | null;
  url: string | null;
  version: Generated<number>;
}

export interface Retirement {
  account_id: string;
  beneficiary_name: string | null;
  beneficiary_organisation_id: string | null;
  block_id: string;
  certificate_document_id: string | null;
  created_at: Generated<Timestamp>;
  detail: string | null;
  id: string;
  modified_at: Generated<Timestamp>;
  project_id: string;
  purpose: string | null;
  quantity: Int8;
  retired_at: Timestamp;
  version: Generated<number>;
  vintage_label: string;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  checksum: string;
  version: string;
}

export interface SimConfig {
  actions_per_tick: Generated<number>;
  id: Generated<boolean>;
  is_running: Generated<boolean>;
  last_tick_at: Timestamp | null;
  modified_at: Generated<Timestamp>;
  paused_reason: string | null;
  seed: Generated<string>;
  speed: Generated<Numeric>;
  tick_no: Generated<Int8>;
  tick_seconds: Generated<number>;
}

export interface SimRun {
  actions: Generated<Json>;
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  started_at: Timestamp;
  tick_no: Int8;
}

export interface Standard {
  cdop_name: string;
  crediting_program_id: string;
  default_buffer_rate: Numeric | null;
  id: string;
  native_standard_id: string | null;
  registry_id: string;
  short_code: string;
  status_vocabulary: Generated<string>;
  unit_type_pending: string | null;
  unit_type_verified: string;
  verification_schedule: Generated<Json>;
  vintage_period_years: Generated<number>;
}

export interface StandardVersion {
  effective_on: Timestamp | null;
  id: string;
  is_current: Generated<boolean>;
  standard_id: string;
  version: string;
}

export interface Transfer {
  block_id: string;
  created_at: Generated<Timestamp>;
  currency: string | null;
  from_account_id: string;
  id: string;
  kind: string;
  modified_at: Generated<Timestamp>;
  price: Numeric | null;
  project_id: string;
  quantity: Int8;
  remarks: string | null;
  requested_at: Timestamp;
  settled_at: Timestamp | null;
  status: string;
  to_account_id: string;
  version: Generated<number>;
}

export interface UnitBlock {
  block_end: Int8;
  block_start: Int8;
  cancellation_id: string | null;
  cdop_status: string;
  created_at: Generated<Timestamp>;
  id: string;
  issuance_id: string;
  labels_cached: Generated<string[]>;
  metric: Generated<string>;
  modified_at: Generated<Timestamp>;
  native_status_code: string | null;
  native_status_name: string | null;
  owner_account_id: string;
  project_id: string;
  quantity: Generated<Int8 | null>;
  retirement_id: string | null;
  serial_number: string;
  source_block_id: string | null;
  state: string;
  state_reason: string | null;
  unit_class: string;
  unit_type: string;
  version: Generated<number>;
  vintage_end_on: Timestamp;
  vintage_label: string;
  vintage_start_on: Timestamp;
}

export interface UnitLabel {
  accreditation_id: string | null;
  approved_on: Timestamp | null;
  block_id: string;
  expiry_on: Timestamp | null;
  kind: string;
  label_id: string;
  start_on: Timestamp | null;
  url: string | null;
}

export interface UnitStatusHistory {
  action: string;
  actor_account_id: string | null;
  actor_kind: string;
  block_id: string;
  cdop_status: string;
  effective_at: Timestamp;
  event_id: string | null;
  from_owner_account_id: string | null;
  from_state: string | null;
  id: string;
  is_current: Generated<boolean>;
  project_id: string;
  quantity: Int8 | null;
  reason: string | null;
  recorded_at: Generated<Timestamp>;
  sequence: number;
  to_owner_account_id: string | null;
  to_state: string;
}

export interface ValidationEvent {
  created_at: Generated<Timestamp>;
  crediting_period_id: string | null;
  decided_on: Timestamp | null;
  expires_on: Timestamp | null;
  id: string;
  modified_at: Generated<Timestamp>;
  notes: string | null;
  opinion: string | null;
  project_id: string;
  report_document_id: string | null;
  report_url: string | null;
  sequence: number;
  site_visit_end_on: Timestamp | null;
  site_visit_start_on: Timestamp | null;
  statement_document_id: string | null;
  status: string;
  submitted_on: Timestamp | null;
  validation_type: string;
  version: Generated<number>;
  vvb_account_id: string | null;
  vvb_organisation_id: string | null;
}

export interface VerificationEvent {
  buffer_deduction: Generated<Numeric>;
  claim_type: Generated<string>;
  claimed_quantity: Numeric | null;
  created_at: Generated<Timestamp>;
  cumulative_verified_quantity: Numeric | null;
  gross_verified_quantity: Numeric | null;
  id: string;
  issuance_id: string | null;
  leakage_deduction: Generated<Numeric>;
  modified_at: Generated<Timestamp>;
  monitoring_period_end_on: Timestamp;
  monitoring_period_start_on: Timestamp;
  opinion: string | null;
  predicted_quantity: Numeric | null;
  project_id: string;
  report_document_id: string | null;
  report_url: string | null;
  sequence: number;
  site_visit_end_on: Timestamp | null;
  site_visit_start_on: Timestamp | null;
  statement_document_id: string | null;
  status: string;
  submitted_on: Timestamp | null;
  uncertainty_basis: string | null;
  uncertainty_deduction: Generated<Numeric>;
  uncertainty_margin: Numeric | null;
  uom: Generated<string>;
  verified_on: Timestamp | null;
  verified_quantity: Generated<Numeric | null>;
  version: Generated<number>;
  vvb_organisation_id: string | null;
}

export interface Webhook {
  consecutive_failures: Generated<number>;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: string;
  is_enabled: Generated<boolean>;
  modified_at: Generated<Timestamp>;
  owner_api_key_id: string | null;
  project_id: string | null;
  secret_hash: string;
  types: Generated<string[]>;
  url: string;
  version: Generated<number>;
}

export interface WebhookDelivery {
  attempt: Generated<number>;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  event_sequence: Int8;
  id: string;
  last_error: string | null;
  last_response_status: number | null;
  next_attempt_at: Generated<Timestamp>;
  status: string;
  webhook_id: string;
}

export interface DB {
  account: Account;
  agreement: Agreement;
  agreement_counterparty: AgreementCounterparty;
  agreement_funding: AgreementFunding;
  agreement_insurance: AgreementInsurance;
  agreement_offtake: AgreementOfftake;
  api_key: ApiKey;
  buffer_pool_balance: BufferPoolBalance;
  buffer_pool_entry: BufferPoolEntry;
  cancellation: Cancellation;
  cdop_vocabulary: CdopVocabulary;
  cobenefit_impact: CobenefitImpact;
  cobenefit_method: CobenefitMethod;
  cobenefit_target: CobenefitTarget;
  crediting_period: CreditingPeriod;
  crediting_program: CreditingProgram;
  document: Document;
  document_type: DocumentType;
  estimation: Estimation;
  estimation_vintage: EstimationVintage;
  event: Event;
  geolocation_file: GeolocationFile;
  idempotency_key: IdempotencyKey;
  issuance: Issuance;
  label: Label;
  lifecycle_transition: LifecycleTransition;
  methodology: Methodology;
  methodology_version: MethodologyVersion;
  milestone: Milestone;
  native_state: NativeState;
  native_transition: NativeTransition;
  organisation: Organisation;
  project: Project;
  project_finance: ProjectFinance;
  project_label: ProjectLabel;
  project_landowner: ProjectLandowner;
  project_location: ProjectLocation;
  project_mitigation: ProjectMitigation;
  project_registry_history: ProjectRegistryHistory;
  project_sdg: ProjectSdg;
  project_stakeholder: ProjectStakeholder;
  project_status_history: ProjectStatusHistory;
  registry: Registry;
  retirement: Retirement;
  schema_migrations: SchemaMigrations;
  sim_config: SimConfig;
  sim_run: SimRun;
  standard: Standard;
  standard_version: StandardVersion;
  transfer: Transfer;
  unit_block: UnitBlock;
  unit_label: UnitLabel;
  unit_status_history: UnitStatusHistory;
  validation_event: ValidationEvent;
  verification_event: VerificationEvent;
  webhook: Webhook;
  webhook_delivery: WebhookDelivery;
}
