/** UK Peatland Code machine on the UK Land Carbon Registry (registry's own action names). */
import type { NativeState, NativeTransition, StandardMachine } from "./types.js";

const S = (
  code: string,
  name: string,
  owner: NativeState["owner"],
  lifecycle: NativeState["lifecycle"],
  cdopStatus: NativeState["cdopStatus"],
  phase?: string,
  terminal = false,
): NativeState => {
  const s: NativeState = { code, name, owner, lifecycle, cdopStatus, terminal };
  if (phase) s.phase = phase;
  return s;
};
const T = (
  from: string,
  action: string,
  actor: NativeTransition["actor"],
  intent: NativeTransition["intent"],
  to: string,
  label: string,
  requiresReason = false,
): NativeTransition => ({
  from,
  action,
  actor,
  intent,
  to,
  label,
  requiresReason,
});

export const PC_STATES: NativeState[] = [
  S("NEW", "New", "developer", "draft", "Project design drafting"),
  S(
    "PENDING_CUST_DEV",
    "Under Development - Pending Review (Customer)",
    "developer",
    "draft",
    "Project design finalization",
    "registration_review",
  ),
  S(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_3RD_PARTY",
    "Under Development - Pending Review (Program)",
    "code_admin",
    "draft",
    "Project design finalization",
    "registration_review",
  ),
  S(
    "PENDING_MOP_UNDER_DEV",
    "Under Development - Pending Review (System)",
    "registry",
    "draft",
    "Project design finalization",
    "registration_review",
  ),
  S("DEVELOPMENT", "Under Development", "developer", "registered", "Registered"),
  S(
    "PENDING_REVIEW_VALIDATION_CUSTOMER",
    "Pending Review (Customer)",
    "developer",
    "registered",
    "Validation",
    "validation_review",
  ),
  S(
    "PENDING_REVIEW_VALIDATION_VALIDATOR",
    "Pending Review (Validator)",
    "vvb",
    "registered",
    "Validation",
    "validation_review",
  ),
  S(
    "PENDING_3RD_VAL",
    "Pending Review (Program)",
    "code_admin",
    "registered",
    "Validation",
    "validation_review",
  ),
  S(
    "PENDING_REVIEW_VALIDATION_MARKIT",
    "Pending Review (System)",
    "registry",
    "registered",
    "Validation",
    "validation_review",
  ),
  S(
    "VALIDATED_PENDING_PAYMENT",
    "Validated - Pending Payment",
    "registry",
    "registered",
    "Validation",
    "payment_hold",
  ),
  S("VALIDATED", "Validated", "registry", "validated", "Validated"),
  S(
    "PENDING_VALIDATOR_RESTORATION_VALIDATION",
    "Pending Restoration Validation (Validator)",
    "vvb",
    "validated",
    "Validated",
    "restoration_validation",
  ),
  S(
    "PENDING_MOP_RESTORATION_VALIDATION",
    "Pending Restoration Validation (System)",
    "registry",
    "validated",
    "Validated",
    "restoration_validation",
  ),
  S(
    "RESTORATION_VALIDATED",
    "Restoration Validated",
    "registry",
    "validated",
    "Validated",
    "restoration_validated",
  ),
  S("VERIFIED", "Verified", "registry", "verified", "Verified and issuing"),
  S("RETIRED", "Retired", "developer", "retired", "Completed", undefined, true),
  S("WITHDRAWN", "Withdrawn", "developer", "withdrawn", "Withdrawn", undefined, true),
  S("REJECTED", "Rejected", "registry", "rejected", "Rejected", undefined, true),
];

export const PC_TRANSITIONS: NativeTransition[] = [
  T(
    "NEW",
    "SUBMIT_PROJECT",
    "developer",
    "submit",
    "PENDING_REVIEW_UNDER_DEVELOPMENT_3RD_PARTY",
    "Submit for registration",
  ),
  T(
    "PENDING_CUST_DEV",
    "SUBMIT_PROJECT",
    "developer",
    "submit",
    "PENDING_REVIEW_UNDER_DEVELOPMENT_3RD_PARTY",
    "Resubmit for registration",
  ),
  T(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_3RD_PARTY",
    "PROGRAM_ADMIN_UNDER_DEVELOPMENT_APPROVE_PROJECT",
    "code_admin",
    "approve",
    "PENDING_MOP_UNDER_DEV",
    "Approve",
  ),
  T(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_3RD_PARTY",
    "PROGRAM_ADMIN_UNDER_DEVELOPMENT_NEED_MORE_INFO_PROJECT",
    "code_admin",
    "more_info",
    "PENDING_CUST_DEV",
    "Send back for more information",
    true,
  ),
  T(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_3RD_PARTY",
    "PROGRAM_ADMIN_UNDER_DEVELOPMENT_REJECT_PROJECT",
    "code_admin",
    "reject",
    "REJECTED",
    "Reject the project",
    true,
  ),
  T(
    "PENDING_MOP_UNDER_DEV",
    "REGISTRY_ADMIN_UNDER_DEVELOPMENT_APPROVE_PROJECT",
    "registry",
    "approve",
    "DEVELOPMENT",
    "Approve",
  ),
  T(
    "PENDING_MOP_UNDER_DEV",
    "REGISTRY_ADMIN_UNDER_DEVELOPMENT_NEED_MORE_INFO_PROJECT",
    "registry",
    "more_info",
    "PENDING_REVIEW_UNDER_DEVELOPMENT_3RD_PARTY",
    "Send back for more information",
    true,
  ),
  T(
    "PENDING_MOP_UNDER_DEV",
    "REGISTRY_ADMIN_UNDER_DEVELOPMENT_REJECT_PROJECT",
    "registry",
    "reject",
    "REJECTED",
    "Reject the project",
    true,
  ),
  T(
    "DEVELOPMENT",
    "VALIDATE_PROJECT",
    "developer",
    "submit",
    "PENDING_REVIEW_VALIDATION_VALIDATOR",
    "Submit for validation",
  ),
  T("DEVELOPMENT", "WITHDRAW", "developer", "withdraw", "WITHDRAWN", "Withdraw the project", true),
  T(
    "PENDING_REVIEW_VALIDATION_CUSTOMER",
    "VALIDATE_PROJECT",
    "developer",
    "submit",
    "PENDING_REVIEW_VALIDATION_VALIDATOR",
    "Resubmit for validation",
  ),
  T(
    "PENDING_REVIEW_VALIDATION_VALIDATOR",
    "VALIDATOR_VALIDATE_PROJECT",
    "vvb",
    "approve",
    "PENDING_3RD_VAL",
    "Approve",
  ),
  T(
    "PENDING_REVIEW_VALIDATION_VALIDATOR",
    "VALIDATOR_NEED_MORE_INFO_PROJECT",
    "vvb",
    "more_info",
    "PENDING_REVIEW_VALIDATION_CUSTOMER",
    "Send back for more information",
    true,
  ),
  T(
    "PENDING_REVIEW_VALIDATION_VALIDATOR",
    "VALIDATOR_REJECT_PROJECT",
    "vvb",
    "reject",
    "DEVELOPMENT",
    "Reject the pack",
    true,
  ),
  T(
    "PENDING_3RD_VAL",
    "PROGRAM_ADMIN_APPROVE_PROJECT",
    "code_admin",
    "approve",
    "PENDING_REVIEW_VALIDATION_MARKIT",
    "Approve",
  ),
  T(
    "PENDING_3RD_VAL",
    "PROGRAM_ADMIN_NEED_MORE_INFO_PROJECT",
    "code_admin",
    "more_info",
    "PENDING_REVIEW_VALIDATION_VALIDATOR",
    "Send back for more information",
    true,
  ),
  T(
    "PENDING_3RD_VAL",
    "PROGRAM_ADMIN_REJECT_PROJECT",
    "code_admin",
    "reject",
    "DEVELOPMENT",
    "Reject",
    true,
  ),
  T(
    "PENDING_REVIEW_VALIDATION_MARKIT",
    "REGISTRY_ADMIN_PENDING_PAYMENT_PROJECT",
    "registry",
    "hold",
    "VALIDATED_PENDING_PAYMENT",
    "Approve and hold for payment",
  ),
  T(
    "PENDING_REVIEW_VALIDATION_MARKIT",
    "REGISTRY_ADMIN_NEED_MORE_INFO_PROJECT",
    "registry",
    "more_info",
    "PENDING_3RD_VAL",
    "Send back for more information",
    true,
  ),
  T(
    "PENDING_REVIEW_VALIDATION_MARKIT",
    "REGISTRY_ADMIN_REJECT_PROJECT",
    "registry",
    "reject",
    "DEVELOPMENT",
    "Reject",
    true,
  ),
  T(
    "VALIDATED_PENDING_PAYMENT",
    "REGISTRY_ADMIN_APPROVE_PROJECT",
    "registry",
    "release",
    "VALIDATED",
    "Release payment and validate",
  ),
  T(
    "VALIDATED",
    "RESTORATION_VALIDATE_PROJECT",
    "developer",
    "submit",
    "PENDING_VALIDATOR_RESTORATION_VALIDATION",
    "Submit restoration for validation",
  ),
  T("VALIDATED", "WITHDRAW", "developer", "withdraw", "WITHDRAWN", "Withdraw the project", true),
  T(
    "PENDING_VALIDATOR_RESTORATION_VALIDATION",
    "VALIDATOR_RESTORATION_VALIDATE_PROJECT",
    "vvb",
    "approve",
    "PENDING_MOP_RESTORATION_VALIDATION",
    "Approve restoration",
  ),
  T(
    "PENDING_VALIDATOR_RESTORATION_VALIDATION",
    "VALIDATOR_RESTORATION_NEED_MORE_INFO_PROJECT",
    "vvb",
    "more_info",
    "VALIDATED",
    "Send back for more information",
    true,
  ),
  T(
    "PENDING_MOP_RESTORATION_VALIDATION",
    "REGISTRY_ADMIN_RESTORATION_VALIDATE_PROJECT",
    "registry",
    "approve",
    "RESTORATION_VALIDATED",
    "Confirm restoration validated",
  ),
  T(
    "RESTORATION_VALIDATED",
    "VERIFY",
    "registry",
    "verify",
    "VERIFIED",
    "Record verification and convert units",
  ),
  T("VERIFIED", "VERIFY", "registry", "verify", "VERIFIED", "Record a further verification"),
  T(
    "VERIFIED",
    "RETIRE_PROJECT",
    "registry",
    "other",
    "RETIRED",
    "Close the project after the final verification",
  ),
];

export const PC_MACHINE: StandardMachine = {
  standardId: "pc",
  states: PC_STATES,
  transitions: PC_TRANSITIONS,
};
