/**
 * UK Woodland Carbon Code state machine on the UK Land Carbon Registry (S&P Global), ported
 * from the Rethink platform's mirror (lib/registry-transitions.ts + lib/registry-state.ts).
 * Action names are the registry's own. Verification / not-delivered / withdrawal edges are
 * added from the observed post-validation states so the simulator can drive a full lifecycle.
 */
import type { NativeState, NativeTransition, StandardMachine } from "./types.js";

const S = (
  code: string,
  name: string,
  owner: NativeState["owner"],
  lifecycle: NativeState["lifecycle"],
  cdopStatus: NativeState["cdopStatus"],
  phase?: string,
  terminal = false,
): NativeState => {
  const s: NativeState = { code, name, owner, lifecycle, cdopStatus, terminal };
  if (phase) s.phase = phase;
  return s;
};

export const WCC_STATES: NativeState[] = [
  S("NEW", "New", "developer", "draft", "Project design drafting"),
  S(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR1",
    "Under Development - Pending Review (Customer)",
    "developer",
    "draft",
    "Project design finalization",
    "registration_review",
  ),
  S(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR2",
    "Under Development - Pending Review (Program)",
    "code_admin",
    "draft",
    "Project design finalization",
    "registration_review",
  ),
  S(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR3",
    "Under Development - Pending Review (System)",
    "registry",
    "draft",
    "Project design finalization",
    "registration_review",
  ),
  S("DEVELOPMENT", "Under Development", "developer", "registered", "Registered"),
  S(
    "PENDING_REVIEW_ACTOR4",
    "Pending Review (Customer)",
    "developer",
    "registered",
    "Validation",
    "validation_review",
  ),
  S(
    "PENDING_REVIEW_ACTOR5",
    "Pending Review (Validator)",
    "vvb",
    "registered",
    "Validation",
    "validation_review",
  ),
  S(
    "PENDING_REVIEW_ACTOR6",
    "Pending Review (Program)",
    "code_admin",
    "registered",
    "Validation",
    "validation_review",
  ),
  S(
    "PENDING_REVIEW_ACTOR7",
    "Pending Review (System)",
    "registry",
    "registered",
    "Validation",
    "validation_review",
  ),
  S(
    "PENDING_PAYMENT_ACTOR7",
    "Pending Payment",
    "registry",
    "registered",
    "Validation",
    "payment_hold",
  ),
  S("VALIDATED", "Validated", "registry", "validated", "Validated"),
  S("SELF_ASSESSED", "Self Assessed", "developer", "validated", "Validated", "self_assessed"),
  S("VERIFIED", "Verified", "registry", "verified", "Verified and issuing"),
  S(
    "NOT_DELIVERED",
    "Not Delivered",
    "code_admin",
    "withdrawn",
    "De-registered",
    "not_delivered",
    true,
  ),
  S("RETIRED", "Retired", "developer", "retired", "Completed", undefined, true),
  S("WITHDRAWN", "Withdrawn", "developer", "withdrawn", "Withdrawn", undefined, true),
  S("REJECTED", "Rejected", "registry", "rejected", "Rejected", undefined, true),
];

const T = (
  from: string,
  action: string,
  actor: NativeTransition["actor"],
  intent: NativeTransition["intent"],
  to: string,
  label: string,
  requiresReason = false,
): NativeTransition => ({
  from,
  action,
  actor,
  intent,
  to,
  label,
  requiresReason,
});

export const WCC_TRANSITIONS: NativeTransition[] = [
  T(
    "NEW",
    "SUBMIT_ACTOR1",
    "developer",
    "submit",
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR2",
    "Submit for registration",
  ),
  T(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR1",
    "SUBMIT_ACTOR1",
    "developer",
    "submit",
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR2",
    "Resubmit for registration",
  ),
  T(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR2",
    "APPROVE_ACTOR2",
    "code_admin",
    "approve",
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR3",
    "Approve",
  ),
  T(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR2",
    "NEED_MORE_INFORMATION_ACTOR2",
    "code_admin",
    "more_info",
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR1",
    "Send back for more information",
    true,
  ),
  T(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR2",
    "REJECT_ACTOR2",
    "code_admin",
    "reject",
    "REJECTED",
    "Reject the project",
    true,
  ),
  T(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR3",
    "APPROVE_ACTOR3",
    "registry",
    "approve",
    "DEVELOPMENT",
    "Approve",
  ),
  T(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR3",
    "NEED_MORE_INFORMATION_ACTOR3",
    "registry",
    "more_info",
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR2",
    "Send back for more information",
    true,
  ),
  T(
    "PENDING_REVIEW_UNDER_DEVELOPMENT_ACTOR3",
    "REJECT_ACTOR3",
    "registry",
    "reject",
    "REJECTED",
    "Reject the project",
    true,
  ),
  T(
    "DEVELOPMENT",
    "VALIDATE_ACTOR4",
    "developer",
    "submit",
    "PENDING_REVIEW_ACTOR5",
    "Submit for validation",
  ),
  T("DEVELOPMENT", "WITHDRAW", "developer", "withdraw", "WITHDRAWN", "Withdraw the project", true),
  T(
    "DEVELOPMENT",
    "NOT_DELIVERED",
    "code_admin",
    "reject",
    "NOT_DELIVERED",
    "Mark as not delivered (validation deadline passed)",
    true,
  ),
  T(
    "PENDING_REVIEW_ACTOR4",
    "VALIDATE_ACTOR4",
    "developer",
    "submit",
    "PENDING_REVIEW_ACTOR5",
    "Resubmit for validation",
  ),
  T(
    "PENDING_REVIEW_ACTOR5",
    "APPROVE_ACTOR5",
    "vvb",
    "approve",
    "PENDING_REVIEW_ACTOR6",
    "Approve",
  ),
  T(
    "PENDING_REVIEW_ACTOR5",
    "NEED_MORE_INFORMATION_ACTOR5",
    "vvb",
    "more_info",
    "PENDING_REVIEW_ACTOR4",
    "Send back for more information",
    true,
  ),
  T(
    "PENDING_REVIEW_ACTOR5",
    "REJECT_ACTOR5",
    "vvb",
    "reject",
    "DEVELOPMENT",
    "Reject the pack",
    true,
  ),
  T(
    "PENDING_REVIEW_ACTOR6",
    "APPROVE_ACTOR6",
    "code_admin",
    "approve",
    "PENDING_REVIEW_ACTOR7",
    "Approve",
  ),
  T(
    "PENDING_REVIEW_ACTOR6",
    "NEED_MORE_INFORMATION_ACTOR6",
    "code_admin",
    "more_info",
    "PENDING_REVIEW_ACTOR5",
    "Send back for more information",
    true,
  ),
  T(
    "PENDING_REVIEW_ACTOR6",
    "REJECT_ACTOR6",
    "code_admin",
    "reject",
    "DEVELOPMENT",
    "Reject",
    true,
  ),
  T("PENDING_REVIEW_ACTOR7", "APPROVE_ACTOR7", "registry", "approve", "VALIDATED", "Approve"),
  T(
    "PENDING_REVIEW_ACTOR7",
    "PENDING_PAYMENT_ACTOR7",
    "registry",
    "hold",
    "PENDING_PAYMENT_ACTOR7",
    "Hold for payment",
  ),
  T(
    "PENDING_REVIEW_ACTOR7",
    "NEED_MORE_INFORMATION_ACTOR7",
    "registry",
    "more_info",
    "PENDING_REVIEW_ACTOR6",
    "Send back for more information",
    true,
  ),
  T("PENDING_REVIEW_ACTOR7", "REJECT_ACTOR7", "registry", "reject", "DEVELOPMENT", "Reject", true),
  T(
    "PENDING_PAYMENT_ACTOR7",
    "APPROVE_ACTOR7",
    "registry",
    "release",
    "VALIDATED",
    "Release payment and validate",
  ),
  T(
    "VALIDATED",
    "VERIFY",
    "registry",
    "verify",
    "VERIFIED",
    "Record verification and convert units",
  ),
  T("VALIDATED", "WITHDRAW", "developer", "withdraw", "WITHDRAWN", "Withdraw the project", true),
  T("VERIFIED", "VERIFY", "registry", "verify", "VERIFIED", "Record a further verification"),
  T(
    "VERIFIED",
    "RETIRE_PROJECT",
    "registry",
    "other",
    "RETIRED",
    "Close the project after the final verification",
  ),
];

export const WCC_MACHINE: StandardMachine = {
  standardId: "wcc",
  states: WCC_STATES,
  transitions: WCC_TRANSITIONS,
};
